name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg

          # Informações básicas da conta
          base: header, activity

          # Linguagens utilizadas
          plugin_languages: yes

          # Calendário de contribuições
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # Atividade recente
          plugin_activity: yes
          plugin_activity_limit: 5

          config_timezone: America/Recife
